version: "3"

services:
  backend:
    image: index.docker.io/demurewolf/isstracker-backend
    restart: always
    command: uvicorn iss.api:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
    
  frontend:
    image: index.docker.io/demurewolf/isstracker-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx-iss.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  watchtower:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
